title: Sanjay Azad
description: Knowledge sharing pages
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

permalink: pretty

url: https://sanjay-azad.github.io/en

aux_links: # remove if you don't want this link to appear on your pages
   # Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
   Book a meeting: https://topmate.io/sanjayazad


# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

# exclude:
#    - Gemfile
#    - info.md

# For copy button on code
enable_copy_code_button: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_external_links:
  - title: The Book
    url: https://sanjay-azad.github.io/home/
  - title: Sanjay on LinkedIn
    url: https://linkedin.com/in/sanjay-azad-1a368187


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; 2023 | Sanjay Azad"

callouts:
  highlight:
    color: purple
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red



