title: Sanjay Azad
description: Knowledge sharing pages
remote_theme: pmarsceill/just-the-docs

permalink: pretty

url: https://sanjay-azad.github.io/en

aux_links: # remove if you don't want this link to appear on your pages
   # Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
   Book a meeting: https://topmate.io/sanjayazad


# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

exclude:
   - Gemfile
   - info.md

# For copy button on code
enable_copy_code_button: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_external_links:
  - title: Connect to me on LinkedIn
    url: https://linkedin.com/in/sanjay-azad-1a368187


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; 2023 | Sanjay Azad"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Google analytics
ga_tracking: G-LN5CP3J3JZ
ga_tracking_anonymize_ip: false



