title: Sanjay Azad
description: Knowledge sharing pages
theme: just-the-docs

url: https://sanjay-azad.github.io/en

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
